// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseAccessToken } from './authClient';

const SUPABASE_URL = "https://hwwjwkdbautfkhpxuord.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3d2p3a2RiYXV0ZmtocHh1b3JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzNzkwNDAsImV4cCI6MjA4OTk1NTA0MH0.PN9xhG95nXlaUJn5DmtoQJ62yn3XJWOsHvZyQF8Zq2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// !! If this file is regenerated, the `accessToken` line below must be put back
// !! or authentication breaks: without it the client stops sending Clerk tokens
// !! and signs every request with its own session instead. The logic itself
// !! lives in ./authClient so a regeneration only costs this one line.
//
// Supplying `accessToken` also disables this client's own auth — supabase-js
// replaces `.auth` with a proxy that throws — which is why Supabase sign-in,
// recovery and sign-out all go through supabaseAuth in ./authClient instead.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  accessToken: getSupabaseAccessToken,
});